### ISSUE TITLE
Global auf EU umschalten

### ISSUE THREAD

**Issue by Wunni73** [nograx/ioBroker.zendure-solarflow#18]
in Admin in IOBroker Setup eine Auswahl zwischen EU und Global einfügen.

Damit man seinen Server auswählen kann.

**Comment by nograx** [comment]
Hi, I have only one Solarflow device for testing. It is running great on the global server - so I'm not planning to implement the EU server as I have to take down my own system for implementing this. This will cost time an money I don't have. I hope that zendure will add local mqtt support which will fix a lot. I'm sorry.
