### ISSUE TITLE
activate the adapter - no values

### ISSUE THREAD

**Issue by markushoedl** [nograx/ioBroker.zendure-solarflow#20]
**Describe the bug**  
I activated the adapter - there is just the event: "Getting device list from Zendure Rest API!"
But no devices.

**To Reproduce**  
Tried several times. On the App there is an logoff - all events in iobroker show ok - but no values

**Expected behavior**  
see some values under the folder "zendure solarflow"

**Screenshots & Logfiles**  
![image](https://github.com/nograx/ioBroker.zendure-solarflow/assets/151467919/3b37a077-9898-48bf-b5b0-5492a5449011)
![image](https://github.com/nograx/ioBroker.zendure-solarflow/assets/151467919/7db57853-5efe-487e-bf23-d3f745369c9c)

**Versions:**  
 - Adapter version: v1.0.7
 - JS-Controller version: < v 5.0.16
 - Node version: v18.16.0
 - Operating system: Docker

**Comment by nograx** [comment]
Die you natives that your SolarFlow Hub has to registered in the global Server?

**Comment by markushoedl** [comment]
ok now I get some values. some are not updating

![image](https://github.com/nograx/ioBroker.zendure-solarflow/assets/151467919/d247f25f-5d98-4e2c-9cb1-a10a9fb49111)

**Comment by nograx** [comment]
Don‘t use the App if you wish to use the Adapter. You will be logged out if you start the App. It‘s possible to use a second account. States will ne Updated as soon as a new value will be sent from the Hub.
