### ISSUE TITLE
Error „Retrieving device failed“ ever now and then

### ISSUE THREAD

**Issue by andiweli** [nograx/ioBroker.zendure-solarflow#24]
**Describe the bug**  
Error in Log „ zendure-solarflow.0
2024-02-16 19:53:55.324	error	Retrieving device failed!“

I am logged in and everything seems to work.
But every now and then I see this error in the Log…

**Comment by andiweli** [comment]
"Every now and then" seems to be more often now...
![Bildschirmfoto 2024-02-19 um 09 57 28](https://github.com/nograx/ioBroker.zendure-solarflow/assets/11447150/567f3f08-3506-4344-9e48-47be15ddae31)

**Comment by nograx** [comment]
I have adjusted the timeout values to give the server more time to respond. Please check version 1.1.4 if the behavior is better now.

**Comment by andiweli** [comment]
So far no errors anymore :) Thanks

**Comment by nograx** [comment]
Perfect, will close this for now.
