### ISSUE TITLE
Bypass Status via MQTT

### ISSUE THREAD

**Issue by HC-Hofer** [nograx/ioBroker.zendure-solarflow#31]
Is it possible to query the bypass status via MQTT?

Found something here in Line 30:
https://github.com/reinhard-brandstaedter/solarflow-control/blob/master/src/solarflow/solarflow.py
[](https://github.com/reinhard-brandstaedter/solarflow-control/blob/master/src/solarflow/solarflow.py)

**Comment by nograx** [comment]
Bypass status and related values are available in the latest version. Will be available in stable channel next week.
