### ISSUE TITLE
energyWh shows wrong Watt

### ISSUE THREAD

**Issue by andiweli** [nograx/ioBroker.zendure-solarflow#35]
**Describe the bug**  
energyWh (Energie in den Batterien (Wh)) shows 7342 Wh.
I only have a max. of 4800 Wh (3x AB1000 + 1x AB2000).
I am using calculations from Adapter, already deleted the whole "calculations" directory.

**Versions:**  
 - Adapter version: 1.1.22
 - JS-Controller version: 5.0.19
 - Node version: 18.19.1
 - Operating system: Raspberry OS Lite Bookworm

**Comment by nograx** [comment]
Please install version 1.2.1 via Github and let the hub charge to 100%. This will set the current energy in batteries as the max value.

**Comment by andiweli** [comment]
@nograx shows 10066,93087389 now. More than 2 times my maximum Wh 😳

**Comment by nograx** [comment]
There is a new version online where you can modify that state. Currently I don't know why this happens. The value if working fine for my system...

**Comment by nograx** [comment]
Hi @andiweli, I have released a prerelease version to GitHub and npm. Could you try these version and bring the HUB to the discharge limit? Then it should reset the maximum Wh values and calculate the correct values afterwards...

**Comment by andiweli** [comment]
HelloThanks for the update - I will try as soon as possible and we have more sun - perhaps the next weekend. ThanksAm 02.04.2024 um 21:01 schrieb Peter ***@***.***>:﻿
Hi @andiweli, I have released a prerelease version to GitHub and npm. Could you try these version and bring the HUB to the discharge limit? Then it should reset the maximum Wh values and calculate the correct values afterwards...

**Comment by nograx** [comment]
Can I close this issue or does it still persist?
