### ISSUE TITLE
IoBroker Adapter fails during firmware update due to JSON parse errors.

### ISSUE THREAD

**Issue by jafrka** [nograx/ioBroker.zendure-solarflow#37]
**Describe the bug**  
The adapter failed during a firmware update. Non-JSON text is delivered and caused the JSON.parse to fail. 

**To Reproduce**  
1. Firmware Update

**Expected behavior**  
Adapter doesn't fail

**Screenshots & Logfiles**  
Don't have it my log files anymore

**Versions:**  
1.1.20

**Additional context**  
I put a try around the JSON parse in my fork to prevent it in the future. Don't know whether there is a better solution.

**Comment by nograx** [comment]
Fixed in Version 1.4.0, unfortunately this can not be tested... I have used your suggestion but need to add typescript interfaces for the MQTT messages.
