### ISSUE TITLE
Vorschläge

### ISSUE THREAD

**Issue by funflo** [nograx/ioBroker.zendure-solarflow#39]
Moin, ich habe mehrere Vorschläge für zukünftige updates:

1. Hub Status Online/offline
2. Schalt Stellung das der hub bei Zuwenig Strom ausgeht (aktuelle Stellung)
3. Aus dem vorherigen auch die Kontrolle

**Comment by nograx** [comment]
Ist alles (bereits seit längerem) umgesetzt. :)
