### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [nograx/ioBroker.zendure-solarflow#40]
👀 [W171] "common.title" is deprecated in [io-package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/io-package.json). Please remove from [io-package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/io-package.json).
 👀 [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
 👀 [W181] "common.license" in [io-package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/io-package.json) is deprecated. Please define object "common.licenseInformation"
 👀 [W173] "@iobroker/adapter-core" (^3.0.4) should be 3.0.6 or newer - please update
 👀 [W115] common.tier is required in [io-package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/io-package.json). Please check https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#adapter.

**Comment by nograx** [comment]
Fixed all poins except W156 ... I'm using React based UI.

**Comment by mcm1957** [comment]
Thanks. 
Everythings fine.
