### ISSUE TITLE
Werte der Parameter name, productName, snNumber immer NULL, API Parameter packNum fehlt gänzlich.

### ISSUE THREAD

**Issue by AndreasFrankeSL** [nograx/ioBroker.zendure-solarflow#44]
**Describe the bug**  
Werte der Parameter name, productName, snNumber immer NULL, API Parameter packNum fehlt gänzlich im Adapter.

![Unbenannt](https://github.com/nograx/ioBroker.zendure-solarflow/assets/61082272/7624cb2a-bd76-4e9d-8b15-e16081105b75)
**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.5.3

**Additional context**

**Comment by nograx** [comment]
These states should be available in the latest version in the beta repository.
