### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [nograx/ioBroker.zendure-solarflow#47]
❗ [E033] @iobroker/adapter-core 3.0.6 specified. 3.1.4 is required as minimum, 3.1.4 is recommended. Please update dependencies at [package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/package.json)

 👀 [W184] "common.main" is deprecated and ignored. Please remove from [io-package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/io-package.json). Use "main" at [package.json](https://github.com/nograx/ioBroker.zendure-solarflow/blob/master/package.json) instead.

**Comment by nograx** [comment]
Fixed in 1.7.0
