### ISSUE TITLE
Connection to MQTT failed! Error: Error: connack timeout

### ISSUE THREAD

**Issue by GM-Jokemaster** [nograx/ioBroker.zendure-solarflow#49]
Adapter is workin good!
But Bombardment into IOB Logs with the newly implementet Test MQTT Test in Version v1.6.4 -> [https://forum.iobroker.net/post/1171641](url)

![grafik](https://github.com/nograx/ioBroker.zendure-solarflow/assets/44427914/fc79526c-7bce-4f39-a829-1c9496a4b39e)

Maybe implement a on/off button for the "additional MQTT Check" ??

Update: 
![grafik](https://github.com/nograx/ioBroker.zendure-solarflow/assets/44427914/86c79053-f907-49f6-8d16-9419a67dda1d)

**Comment by Kiter1988** [comment]
Here too.

**Comment by nograx** [comment]
Please update to 1.6.7 and check if issue still persist.
