### ISSUE TITLE
Enhancement: Add Tibber Pulse Bridge as energy meter

### ISSUE THREAD

**Issue by floriangrotz** [nograx/ioBroker.zendure-solarflow#53]
@HC-Hofer - first thank you so much for your work! 

As an enhancement I would wish for an integration of the Tibber Pulse (instead of a Shelly) 
--> Zero Changes in your power infrastructure

You can gather the data from 

a) TibberLink - https://github.com/hombach/ioBroker.tibberlink

minPower - the day current minimal consumption --> standard which should flow into the house 
PowerConsumtion - the current power consumtion updated every 2 sec ---> can be utilized as zero power from Grid

You could create scenarios - e.g. if someone want to use the Hyper2000 and fuel up the battery
When prices cheap - utilize only minPower -> consume from Grid
When prices not cheap - utilize stable minPower + variable from PowerConsumtion 

<img width="920" alt="tibberlink" src="https://github.com/user-attachments/assets/1aab18be-95c1-476a-8abb-44420244f164">

b) or via the local network from the Tibber Pulse Bridge
https://forum.iobroker.net/topic/70758/tibber-pulse-verbrauchsdaten-lokal-auslesen

**Comment by nograx** [comment]
Hi,

first I think you mentioned the wrong person ;-) me is the author of this adapter.

I don't see any benefit to integrate tibber directly - also every user has his own parameters so it won't be easy to find the one and only solution. If you wan't to get a zero-feed-in solution you can use the data from the tibberlink adapter and create an script/blockly to adjust the "setOutputLimit" parameter in the control folder. With this, you can create your own solution.

Kind regards,
Peter
