### ISSUE TITLE
Fehlender State vom Hyper2000 - Temperaratur

### ISSUE THREAD

**Issue by virus18** [nograx/ioBroker.zendure-solarflow#54]
Hey @nograx ,

vielen Dank erst mal für den Adapter!

Mir ist aufgefallen das ein Datenpunkt noch in der Auflistung fehlt, und das ist die Temperatur vom Hyper.

Finde ich schon nicht verkehrt diesen auch zu abonnieren.

der kommt gelegentlich mal über die States mit,
Und warum sollte man diesen dann nicht direkt mit abgreifen. :-)

Vielen Dank und happy coding.

**Comment by nograx** [comment]
Temperatur ist in 1.7.5 als State verfügbar.
