### ISSUE TITLE
Hyper2000 Bug SetInputLimit & SetOutputLimit - einige Werte nicht übernommen

### ISSUE THREAD

**Issue by floriangrotz** [nograx/ioBroker.zendure-solarflow#55]
Edit - grad mitbekommen das wir schon bei 1.7.6 sind - leider nocht nicht im beta-channel bei iobroker - sorry.
Wenn das unten noch hilfreich ist, gut, wenn nein bitte einfach nochmal schliessen - again sorry

Der Hyper2000 hat technisch ein OutputLimit und ein InputLimit von entweder 0W oder 30W - 1200W in 1W Schritten
Tests:

**SetOutputLimit (an das Hausnetz)**
0W - OK 
1W-29W (technisch nicht möglich - OK
30W -59W - Fehler, wird nicht übernommen
60W - 1200W - OK

**SetInputLimit (vom Grid)**
0W - OK
1W-29W (technisch nicht möglich - OK 
30W - 99W - Fehler, wird nicht übernommen
100W - 900W - OK
901W-1200W - Fehler, wird nicht übernommen

Genereller Fehler (? oder bin ich zu doof) - man muss in die App nochmal gehen wenn man zwischen Output und Input umschalten möchte (speicher in der App) - oder was wäre der richtige weg?

**Versions:**  
 - Adapter version: 1.7.2 beta
 - JS-Controller version: 6.09
 - Operating system: Docker

**Comment by nograx** [comment]
Ich denke mit der 1.7.7 die ich soeben veröffentlich habe sollte das Problem gelöst sein. Heute ist eine Installation per Github möglich (ioBroker auf Expertenmodus stellen und das Github Symbol unter Adapter anklicken). Ansonsten morgen per Beta Kanal.
