### ISSUE TITLE
calcualtions of adapter show strange values

### ISSUE THREAD

**Issue by Totte23** [nograx/ioBroker.zendure-solarflow#56]
Hi, 

It seems that the calculation function of the adapter shows strange values.
For sure I can tell that SOC and solarInputEnergyTodayWh under "Calculations" show values that do not fit...
Is there anything I need to configure?

For SOC the value in calcualtion differs minimum by 20% from the value that is shown in the main tree

Currently I am running 1.7.7 of adapter

Thank you for some feedback / guidance...

best regards

**Comment by nograx** [comment]
Should be fixed with 1.8.1. Please try and report if issue is solved.

**Comment by Totte23** [comment]
Hi, seems to be OK! Thanks a lot!
