### ISSUE TITLE
With 1.8.3 get warn message

### ISSUE THREAD

**Issue by Amutep** [nograx/ioBroker.zendure-solarflow#58]
Hello

with the new 1.8.3 version i get warn message:

State "zendure-solarflow.0.gDa3tb.4U2L3G92.calculations.gridInputEnergyTodaykWh" has no existing object, this might lead to an error in future versions

in object this value show me (null)Wh, (null)kWh

thx

**Comment by nograx** [comment]
Should be fixed with 1.8.4.

**Comment by Amutep** [comment]
no more warn messages thx
